---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest

ansible_config: 'config_for_ee/ansible.cfg'

dependencies:
  galaxy: collections/requirements.yml
  python: requirements.txt

additional_build_steps:
  append:
    - ENV ANSIBLE_CONFIG /etc/ansible/ansible.cfg
    - COPY _build/ansible.cfg /etc/ansible/ansible.cfg
