---
- name: Make sure whether the tenant has the prefixes
  ansible.builtin.set_fact:
    tenant_prefixes: >-
      {{ query('netbox.netbox.nb_lookup',
               'prefixes',
               api_endpoint=netbox_url,
               token=netbox_token,
               api_filter='tenant=%s' % (tenant_name)
         )
      }}

- name: Set target_prefix variable
  ansible.builtin.set_fact:
    target_prefix: "{{ item.value.prefix }}"
  loop: "{{ tenant_prefixes }}"
  when:
    - "'tenant' in item.value"
    - item.value.tenant
    - item.value.tenant.name == tenant_name

- name: Make sure whether a valid prefix does exist in the tenant
  ansible.builtin.assert:
    that:
      - target_prefix is defined
    fail_msg: "Not found a valid prefix in the tenant."
