---
- when:
    - state is not defined or
      state == 'present'
  block:
    - name: Include netbox_add_virtual_machine tasks
      ansible.builtin.include_tasks: netbox_add_virtual_machine.yml

    - name: Include netbox_assign_vm tasks
      ansible.builtin.include_tasks: netbox_assign_vm.yml

- when:
    - state == 'absent'
  block:
    - name: Include netbox_del_virtual_machine tasks
      ansible.builtin.include_tasks: netbox_del_virtual_machine.yml
