---
- name: Delete a virtual machine from NetBox
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.vm_name }}"
      tenant: "{{ tenant_name }}"
    state: absent
  loop: "{{ target_vm_info }}"
