---
- name: Assign IP address to the virtual machine
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      tenant: "{{ tenant_name }}"
      address: "{{ item.1.ip + '/' + item.1.netmask }}"
      assigned_object:
        virtual_machine: "{{ item.0.vm_name }}"
    query_params:
      - address
  loop: "{{ target_vm_info | subelements('networks') }}"

- name: Add IP address to the virtual machine
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.0.vm_name }}"
      cluster: "{{ cluster_name }}"
      tenant: "{{ tenant_name }}"
      primary_ip4: "{{ item.1.ip + '/' + __prefix }}"
  vars:
    __prefix: "{{ prefix | ansible.utils.ipaddr('prefix') }}"
  loop: "{{ target_vm_info | subelements('networks') }}"
