---
argument_specs:
  main:
    short_description: "The variables are used in running the role"
    options:
      datacenter_name:
        type: str
        required: true
        description: "The datacenter name to deploy vm"
      cluster_name:
        type: str
        required: false
        description: "The cluster name to deploy vm"
      esxi_hostname:
        type: str
        required: false
        description: "The ESXi name to deploy vm"
      template_name:
        type: str
        required: true
        description: "The template name"
      dns_ip_addrs:
        type: list
        elements: str
        required: false
        description: "The dns servers to set into vm"
